# Generated by Django 5.2.15 on 2026-06-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesettings',
            name='auto_approve_high_confidence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacesettings',
            name='linear_team_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
