# Generated by Django 5.2.15 on 2026-06-29 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('assignee', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('source_quote', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('discarded', 'Discarded')], default='pending', max_length=20)),
                ('tracker_issue_key', models.CharField(blank=True, max_length=30)),
                ('tracker_type', models.CharField(blank=True, choices=[('linear', 'Linear'), ('jira', 'Jira')], max_length=10)),
                ('push_error', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions_app.meetingsession')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
