# Generated by Django 5.2.15 on 2026-06-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extractedticket',
            options={'ordering': ['extraction_confidence', 'id']},
        ),
        migrations.AddField(
            model_name='extractedticket',
            name='commitment_type',
            field=models.CharField(blank=True, default='implied', max_length=10),
        ),
        migrations.AddField(
            model_name='extractedticket',
            name='confidence_factors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='extractedticket',
            name='confidence_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extractedticket',
            name='extraction_confidence',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='extractedticket',
            name='grounded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='extractedticket',
            name='match_action',
            field=models.CharField(blank=True, choices=[('create_new', 'Create new'), ('update_existing', 'Update existing'), ('link_duplicate', 'Link duplicate'), ('skip_done', 'Skip (done)')], default='create_new', max_length=20),
        ),
        migrations.AddField(
            model_name='extractedticket',
            name='match_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedticket',
            name='match_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extractedticket',
            name='matched_issue_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='extractedticket',
            name='matched_issue_key',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
