# Generated by Django 5.2.15 on 2026-06-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsession',
            name='transcript_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='meetingsession',
            name='input_type',
            field=models.CharField(choices=[('transcript', 'Pasted Transcript'), ('document', 'Uploaded Document'), ('audio', 'Audio/Video')], max_length=20),
        ),
    ]
