# Generated by Django 5.2.15 on 2026-06-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0002_meetingsession_transcript_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsession',
            name='extraction_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='meetingsession',
            name='linear_team_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='meetingsession',
            name='project_key',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
