# Generated by Django 5.2.15 on 2026-08-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0003_meetingsession_extraction_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsession',
            name='processing_stage',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
