# Generated by Django 5.2.15 on 2026-08-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0004_meetingsession_processing_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsession',
            name='processing_detail',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
